#include "nios2_ctrl_reg_macros.h"
#include "globals.h"
#include "keyboard.h"
#include "serial.h"
#include "ui.h"
#include "graphics.h"

#define SCREEN_WIDTH 319
#define SCREEN_HEIGHT 239

/* these globals are written by interrupt service routines; we have to declare 
 * these as volatile to avoid the compiler caching their values in registers */
extern volatile char byte1, byte2, byte3;			/* modified by PS/2 interrupt service routine */
extern volatile int record, play, buffer_index;	// used for audio
extern volatile int timeout;							// used to synchronize with the timer
extern volatile char *kbBuf;  // Use to store the keyboard input
extern volatile unsigned int kbBufBegin, kbBufEnd; // Used to keep track of the keyboard input
extern volatile int change;//used to check change of input
extern volatile int packet1;
extern volatile int packetX;
extern volatile int packetY;

int mouseX,
	mouseY,
	lastMouseX = SCREEN_WIDTH/2,
	lastMouseY = SCREEN_HEIGHT/2;
	
const int box_len = 8;

/* function prototypes */
void VGA_subStrn(int, int, volatile char *, unsigned int, unsigned int, unsigned int);
void VGA_text (int, int, char *);
void VGA_box (int, int, int, short);
void fill_screen (int, int, int, int, short);
void HEX_PS2(char, char);

/********************************************************************************
 * This program demonstrates use of the media ports in the DE1 Media Computer
 *
 * It performs the following: 
 *  	1. records audio for about 10 seconds when an interrupt is generated by
 *  	   pressing KEY[1]. LEDG[0] is lit while recording. Audio recording is 
 *  	   controlled by using interrupts
 * 	2. plays the recorded audio when an interrupt is generated by pressing
 * 	   KEY[2]. LEDG[1] is lit while playing. Audio playback is controlled by 
 * 	   using interrupts
 * 	3. Draws a blue box on the VGA display, and places a text string inside
 * 	   the box. Also, moves the word ALTERA around the display, "bouncing" off
 * 	   the blue box and screen edges
 * 	4. Displays the last two bytes of data received from the PS/2 port 
 * 	   on the HEX displays on the DE1 board. The PS/2 port is handled using 
 * 	   interrupts
 * 	5. The speed of refreshing the VGA screen
 * 	   are controlled by interrupts from the interval timer
********************************************************************************/



int main(void){
	int boardTheirs[] = {
        0,0,0,0,0,0,0,0,0,0,
        0,2,0,0,0,0,8,0,0,0,
        8,0,0,0,0,0,4,0,0,0,
        8,0,0,0,2,0,4,0,0,0,
        8,0,0,8,8,0,0,0,8,0,
        8,0,0,0,2,0,0,0,4,0,
        2,0,0,0,0,0,0,0,8,0,
        0,0,8,4,8,8,4,0,0,0,
        0,0,0,0,0,0,0,2,0,0,
        0,0,0,0,2,0,0,0,0,0,
    };
		int boardYours[] = {
        0,0,0,0,0,0,0,0,0,0,
        0,2,0,0,0,0,8,0,0,0,
        8,0,0,0,0,0,4,0,0,0,
        8,0,0,0,2,0,4,0,0,0,
        8,0,0,8,8,0,0,0,8,0,
        8,0,0,0,2,0,0,0,4,0,
        2,0,0,0,0,0,0,0,8,0,
        0,0,8,4,8,8,4,0,0,0,
        0,0,0,0,0,0,0,2,0,0,
        0,0,0,0,2,0,0,0,0,0,
    };
    //drawBox(0, VGA_HEIGHT-20, 20, 20, colorRGB(0, 255, 0));
		drawBox(0,0,VGA_WIDTH, VGA_HEIGHT, colorRGB(0,0,0));
		displayBoard(boardYours,0);
		displayBoard(boardTheirs,1);
	    while(1){}
	return 0;
}
/****************************************************************************************
 * Subroutine to send a string of text to the VGA monitor 
****************************************************************************************/
void VGA_text(int x, int y, char * text_ptr)
{
	int offset;
  	volatile char * character_buffer = (char *) 0x09000000;	// VGA character buffer
	/* assume that the text string fits on one line */
	offset = (y << 7) + x;
	while ( *(text_ptr) )
	{
		*(character_buffer + offset) = *(text_ptr);	// write to the character buffer
		++text_ptr;
		++offset;
	}
}

char getHexCharacter(const char h) {
    switch(h) {
        case 0x00: return '0';
        case 0x01: return '1';
        case 0x02: return '2';
        case 0x03: return '3';
        case 0x04: return '4';
        case 0x05: return '5';
        case 0x06: return '6';
        case 0x07: return '7';
        case 0x08: return '8';
        case 0x09: return '9';
        case 0x0A: return 'A';
        case 0x0B: return 'B';
        case 0x0C: return 'C';
        case 0x0D: return 'D';
        case 0x0E: return 'E';
        case 0x0F: return 'F';
        default: return '&';
    }
    return '&';
}


void VGA_printKBScanCode(int x, int y) {
    int offset;
  	volatile char * character_buffer = (char *) 0x09000000;	// VGA character buffer
	/* assume that the text string fits on one line */
	offset = (y << 7) + x;
	*(character_buffer + offset) = getHexCharacter((byte2 >> 4) & 0x0F);
    offset++;
    *(character_buffer + offset) = getHexCharacter(byte2 & 0x0F);
}

/****************************************************************************************
 * Subroutine to print a substring to the VGA monitor from a circular buffer
 * x - horizontal location on the screen to start writing the text
 * y - vertical location on the screen to start writing text
 * buffer - circular buffer holding the string to write
 * first - index in the buffer to start writing the string
 * last - index after the last character to write
 * len - length of the buffer
****************************************************************************************/
void VGA_subStrn(int x, int y, volatile char *buffer, unsigned int first, unsigned int last, unsigned int len)
{
	int offset;
  	volatile char * character_buffer = (char *) 0x09000000;	// VGA character buffer
    unsigned int idx = first%len;
    last = last%len;
	/* assume that the text string fits on one line */
	offset = (y << 7) + x;
    while(idx != last)
	{
		*(character_buffer + offset) = buffer[idx];	// write to the character buffer
		++offset;
        idx = (idx+1)%len;
	}
    VGA_printKBScanCode(0, 10);
}

/****************************************************************************************
 * Draw a filled rectangle on the VGA monitor 
****************************************************************************************/
void VGA_box(int x, int y, int len, short pixel_color)
{
	int offset, row, col;
  	volatile short * pixel_buffer = (short *) 0x08000000;	// VGA pixel buffer

	/* assume that the box coordinates are valid */
	for (row = y; row <= y+len; row++)
	{
		col = x;
		while (col <= x+len)
		{
			offset = (row << 9) + col;
			*(pixel_buffer + offset) = pixel_color;	// compute halfword address, set pixel
			++col;
		}
	}
}

/****************************************************************************************
 * Draw a filled rectangle on the VGA monitor 
****************************************************************************************/
void fill_screen(int x1, int y1, int x2, int y2, short pixel_color)
{
	int offset, row, col;
  	volatile short * pixel_buffer = (short *) 0x08000000;	// VGA pixel buffer

	/* assume that the box coordinates are valid */
	for (row = y1; row <= y2; row++)
	{
		col = x1;
		while (col <= x2)
		{
			offset = (row << 9) + col;
			*(pixel_buffer + offset) = pixel_color;	// compute halfword address, set pixel
			++col;
		}
	}
}

/****************************************************************************************
 * Subroutine to show a string of HEX data on the HEX displays
****************************************************************************************/
void HEX_PS2(char b1, char b2)
{
	volatile int * HEX3_HEX0_ptr = (int *) 0x10000020;

	/* SEVEN_SEGMENT_DECODE_TABLE gives the on/off settings for all segments in 
	 * a single 7-seg display in the DE1 Media Computer, for the hex digits 0 - F */
	unsigned char	seven_seg_decode_table[] = {	0x3F, 0x06, 0x5B, 0x4F, 0x66, 0x6D, 0x7D, 0x07, 
		  										0x7F, 0x67, 0x77, 0x7C, 0x39, 0x5E, 0x79, 0x71 };
	unsigned char	hex_segs[] = { 0, 0, 0, 0};
	unsigned int shift_buffer, nibble;
	unsigned char code;
	int i;

	shift_buffer = (b1 << 8) | b2;
	for ( i = 0; i < 4; ++i )
	{
		nibble = shift_buffer & 0x0000000F;		// character is in rightmost nibble
		code = seven_seg_decode_table[nibble];
		hex_segs[i] = code;
		shift_buffer = shift_buffer >> 4;
	}
	/* drive the hex displays */
	*(HEX3_HEX0_ptr) = *(int *) (hex_segs);
}
